tasks:
  research_task:
    description: Conduct a thorough research about {topic}
    expected_output: A list with 5 bullet points of the most relevant information about {topic}
    agent: researcher  

  analysis_task:
    description: Based on the research findings, think about potential innovative research directions that are rarely being researched.
    expected_output: 5 potential research questions or directions, each with justification.
    agent: analyst

  reporting_task:
    description: Summarize the topic, references, and proposed research directions into a report.
      Make sure the report is detailed and formatted in markdown (without backticks).
    expected_output: A fully structured report with main topics and sections.
    agent: writer
